musl: fixes compilation due to missing includes
kitty/keys.c: fix musl compilation
without this include, compilation fails with:
error: 'u_int32_t' undeclared (first use in this function)

kitty/launcher/main.c: fix muls compilation
The fortify header for wchar.h seems to assume that string.h is included
beforehand. Otherwise it fails with the following error:

/usr/include/fortify/string.h:144:1: error: 'mempcpy' undeclared here (not in a funct
144 | _FORTIFY_FN(mempcpy) void *mempcpy(void *__d, const void *__s, size_t __n)
    | ^~~~~~~~~~~

Including string.h fixes the error.